version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2


jobs:

  build: 
    docker:
      - image: cimg/python:3.12-node

    steps:
      - checkout
      - run:
          name: Fetch submodules
          command: |
            git submodule sync --recursive
            git -c submodule.fetchJobs=8 submodule update --recursive --init --jobs 8
      - restore_cache:
          keys:
            - v1-pip-{{ arch }}-{{ checksum "requirements.txt" }}
            - v1-pip-{{ arch }}-
      - restore_cache:
          keys:
            - v1-npm-{{ arch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ arch }}-
      
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - save_cache:
          key: v1-pip-{{ arch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
          
      - run:
          name: Build webpage
          # This assumes pytest is installed via the install-package step above
          command: make

      - save_cache:
          key: v1-npm-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run tests 
          command: echo `pwd` && make test

      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Install awscli
                command: pip install awscli
            - run:
                name: Upload to S3
                command: make upload



workflows:
  build_and_test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
                - beta
    jobs:
      - build
